### PR TITLE
Add array mean function

### PR DESCRIPTION
**Pull request by hur**
Added array mean function and a main() with some test cases.

### CODE REVIEW

**Review by mifrandir — CHANGES_REQUESTED** [review]
The function `array_mean` should be called `arrayMean`.
There is a date missing in the comment at the top of the file.
The indentation in lines 24 and 25 is off.
There is an empty lines at 26 and 28 for no obvious reason.
The function declaration and its comment are missing.
There should be spaces in the for loop (i.e. `for (int i = 0; i < size; ++i`)).

**Comment by hur** [comment]
@MiltFra I've implemented the requested changes.

**Review by mifrandir — APPROVED** [review]

**Comment by mifrandir** [comment]
I don't think it's in the spirit of Hacktoberfest to count this. You did not actually contribute anything to any project because this is just a dummy exercise.

**Comment by hur** [comment]
True, good point.

**Pull request merged**
